name: MLOps Day 2 - Test Training Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'day2_mlops/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/test.yaml'

jobs:
  run-training:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: day2_mlops

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python train.py